YamashitaK-CaseStudy/Case_CESA2023

.vsconfig, Assets/Scenes/SampleScene.unity, Assets/Scripts/PlayerCamera.cs, Assets/Scripts/PlayerCamera.cs.meta, Assets/Scripts/PlayerControl.cs, Assets/Scripts/PlayerControl.cs.meta
プレイヤーの移動処理用のスクリプト　PlayerControl.csを追加しました
プレイヤーを追従するカメラ用スクリプト PlayerCamera.csを追加しました
SampleSceneを一部変更しました
要修正：カメラの追従処理
ジャンプは仮実装です
=> プレイヤーの移動処理

Assets/Scenes/SampleScene.unity, Assets/Scripts/PlayerScript/PlayerAction.cs, Assets/Scripts/PlayerScript/PlayerMove.cs
=> [Update]PlayerAction.csを更新しました

Assets/Scripts/StageObjectScript/RotatableObject.cs
まわす小について,自身の軸と外部の軸で行える関数を実装しました。
アニメーションについては今後実装する予定です。
=> [Update]RotatableObject.csを更新しました

Assets/Editor/CreateObject.cs, Assets/Editor/CreateObject.cs.meta, Assets/Editor/StageEditor.cs, Assets/Prefabs/Stage/Pf_FloarParts.prefab, Assets/Prefabs/Stage/Pf_FloarParts.prefab.meta, Assets/Prefabs/Stage/Pf_MapObjectParts.prefab, Assets/Prefabs/Stage/Pf_MapObjectParts.prefab.meta, Assets/Prefabs/Stage/Pf_Stair.prefab, Assets/Prefabs/Stage/Pf_Stair.prefab.meta, Assets/Scenes/MovieScene/MovieScene1.unity, Assets/Scenes/ProtTypeStage.unity, Assets/Scenes/ProtTypeStage.unity.meta
=> [Update]プロト用のマップの作製

Assets/Scenes/SampleScene.unity, Assets/Scripts/PlayerScript/PlayerAction.cs, Assets/Scripts/PlayerScript/PlayerMove.cs, Assets/Scripts/StageObjectScript/RotatableObject.cs, ProjectSettings/InputManager.asset
自身の軸、外部からの軸でまわす小を実装しました。
[Update]InputManagerを変更しました
InputManagerで"RotateSelfAxis","RotateExturnAxis"を追加しました。それぞれXBOXコントローラーのBボタンとXボタンに対応しています。
[Fix]PlayerAction,csを変更しました
不要な処理を削除しました。オブジェクトが選択されている状態で、ボタンが押された時オブジェクトをまわす処理を呼び出すようにしました。
=> [Update]RotableObject.csを更新しました。

Assets/Prefabs/Stage/Pf_MapObjectParts.prefab, Assets/Prefabs/Stage/Pf_Object.prefab, Assets/Prefabs/Stage/Pf_Object.prefab.meta, Assets/Scenes/ProtTypeStage.unity, Assets/Scripts/PlayerScript/Player.cs, Assets/Scripts/PlayerScript/PlayerAction.cs, Assets/Scripts/StageObjectScript/RotatableObject.cs
ゆっくり回転するようになりました。回転時間は_requiredTimeで変更できます(単位はsec)
=> RotatableObject.csを更新しました

Assets/Scenes/SceneManager.asset, Assets/Scenes/StageSelect.unity, Assets/Scenes/StageSelect.unity.meta, Assets/Scripts/Manager/SceneManager.cs, Assets/Scripts/TextStageNum.cs, Assets/Scripts/TextStageNum.cs.meta, ProjectSettings/EditorBuildSettings.asset
=> St stage select scene

Assets/Scenes/SceneManager.asset, Assets/Scripts/Manager/SceneManager.cs
=> St scene manager

Assets/Prefabs/Pf_BaceObject.prefab, Assets/Prefabs/Pf_BaceObject.prefab.meta, Assets/Scenes/Prot2.unity, Assets/Scripts/PlayerScript/PlayerAction.cs, Assets/Scripts/PlayerScript/PlayerPossession.cs, Assets/Scripts/StageObjectScript/RotObjectRotate.cs, Assets/Scripts/StageObjectScript/RotObjectRotate.cs.meta, Assets/Scripts/StageObjectScript/RotObjectSpin.cs, Assets/Scripts/StageObjectScript/RotObjectSpin.cs.meta, Assets/Scripts/StageObjectScript/RotatableObject.cs
[Update]まわす大の挙動の実装ができました
詳しい詳細は聞いてくれたら解説します。
[Update]まわす大をXボタンで呼び出せるようにしました。
まわす大を実行できるのは現時点ではPf_BaceObjectのみなので注意してください。
=> まわす大の挙動の実装

Assets/Prefabs/Pf_BaceObject.prefab, Assets/Scenes/MainScene.meta, Assets/Scenes/Prot2.unity, Assets/Scenes/TestScene.meta, Assets/Scripts/StageObjectScript/RotObjectHit.cs, Assets/Scripts/StageObjectScript/RotObjectHit.cs.meta, Assets/Scripts/StageObjectScript/RotatableObject.cs, Assets/Textures.meta, Assets/Textures/BG.png.meta, Assets/Textures/M_Test.mat, Assets/Textures/M_Test.mat.meta, ProjectSettings/TagManager.asset
・背景用マテリアルテストで作成
・シーンを一部変更
・当たると回転を実装
=> [Add]当たると回転を実装

Assets/Material.meta, Assets/Material/PlayerMat.mat, Assets/Material/PlayerMat.mat.meta, Assets/Material/RotObjMaterial.mat, Assets/Material/RotObjMaterial.mat.meta, Assets/Material/RotShader.shadergraph, Assets/Material/RotShader.shadergraph.meta, Assets/Prefabs/Pf_BaceObject.prefab, Assets/Prefabs/Player/Pf_NewPlayer.prefab, Assets/Prefabs/Player/Pf_NewPlayer.prefab.meta, Assets/Prefabs/Player/Player 1.prefab, Assets/Scenes/Prot2.unity, Assets/Scripts/PlayerScript/HItChect.meta, Assets/Scripts/PlayerScript/HItChect/TouchCollider.cs, Assets/Scripts/PlayerScript/HItChect/TouchCollider.cs.meta, Assets/Scripts/PlayerScript/PlayerAction.cs, Assets/Scripts/PlayerScript/PlayerObjctHitCheck.cs, Assets/Scripts/PlayerScript/PlayerObjctHitCheck.cs.meta, Assets/Scripts/StageObjectScript/RotObjectRotate.cs, Assets/Scripts/StageObjectScript/RotObjectSpin.cs, Assets/Scripts/StageObjectScript/RotatableObject.cs
RotObjectRotate.csを変更しました
StartRotate関数に引数を追加しました。これで任意の軸で回転ができます。
[Add]TouchCollider.csを追加しました。
プレイヤーが観賞できるオブジェクトを識別する用のコリジョンオブジェクトにつけるComponentスクリプトです。
[Update]Playerのプレハブを一部変更しました
[Add]必要なパーツをいろいろ追加しました。
=> [Update]回転の仕様を更新しました

Assets/Editor/CreateFloor.cs, Assets/Editor/CreateFloor.cs.meta, Assets/Editor/StageEditor.cs
=> [Add]ステージエディタの更新

Assets/Prefabs/RotObjectUnionObthber.prefab, Assets/Prefabs/RotObjectUnionObthber.prefab.meta, Assets/Scenes/MainScene/Stage03.unity, Assets/Scenes/MainScene/Stage04.unity
=> [Update]ステージ3,4の修正

Assets/Editor/SceneCreater/SceneEditor.cs, Assets/Editor/StageEditor/CreateRotateObj.cs, Assets/Scenes/MainScene/Stage01.unity, Assets/Scenes/MainScene/Stage02.unity, Assets/Scenes/MainScene/Stage03.unity, Assets/Scenes/MainScene/Stage04.unity
シーンエディタ
・UnionObjのオブザーバーを自動設置するように
ステージエディタ
・オブジェクトの種類を選択するように指定
・RotObjKindsを自動でアタッチするように
シーンの更新
・RotObjKindsが必要なので全部にアタッチしました
=> [Update]エディタの更新

Assets/Scenes/Prot4/Global Volume (1) Profile.asset, Assets/Scenes/Prot4/Global Volume (1) Profile.asset.meta, Assets/Scenes/Prot4/Global Volume Profile 2.asset, Assets/Scenes/Prot4/Global Volume Profile 2.asset.meta, Assets/Scenes/Prot4/test.mat, Assets/Scenes/Prot4/test.mat.meta, Assets/Scenes/Prot4_Profiles.meta, Assets/Scenes/Prot4_Profiles/Post-process Volume Profile.asset, Assets/Scenes/Prot4_Profiles/Post-process Volume Profile.asset.meta, Assets/Scenes/TestScene/KH_CameraStac.meta, Assets/Scenes/TestScene/KH_CameraStac.unity, Assets/Scenes/TestScene/KH_CameraStac.unity.meta, Assets/Scenes/TestScene/KH_CameraStac/Global Volume Profile.asset, Assets/Scenes/TestScene/KH_CameraStac/Global Volume Profile.asset.meta, Assets/URP/Settings/UIrender.asset, Assets/URP/Settings/UIrender.asset.meta, ProjectSettings/BurstAotSettings_WSAPlayer.json
[Add]カメラスタッキングのテスト用のシーンを追加してます
=> [Update]描画手法をForword+に変更しました

Assets/Scripts/PlayerScript/PlayerAction.cs, Assets/Scripts/StageObjectScript/RotObjectHit.cs, Assets/Scripts/StageObjectScript/RotatableObject.cs
=> [Update]連鎖のシステムを修正

Assets/Scenes/TestScene/YK_TestScene.unity, Assets/Scripts/PlayerScript/PlayerAction.cs, Assets/Scripts/PlayerScript/PlayerHP.cs, Assets/Scripts/PlayerScript/PlayerHP.cs.meta, Assets/Scripts/PlayerScript/StickRotAngleInfo.cs, Assets/Scripts/RespawnCollider.cs, Assets/Scripts/RespawnCollider.cs.meta, Assets/Scripts/RespawnPoint.cs, Assets/Scripts/RespawnPoint.cs.meta, Assets/Scripts/StageObjectScript/RotObjUnion.cs, Assets/Scripts/StageObjectScript/RotObjUnionFX.cs, Assets/Scripts/StageObjectScript/RotObjUnionFX.cs.meta, Assets/Scripts/StageObjectScript/RotObjectRotate.cs, Assets/VFXdeta/New VFX.prefab, Assets/VFXdeta/New VFX.vfx
・磁石のオブジェクトで発生するエフェクトの仮実装
・HPシステムの作成
・リスポーンシステムの作成
=> [Add]エフェクトの作成

Assets/Prefabs/Player/Pf_Player.prefab
=> [Fix]リジットボディを撤去

Assets/Scripts/PlayerScript/PlayerAction.cs, Assets/Scripts/PlayerScript/PlayerMove.cs, Assets/Scripts/PlayerScript/PlayerRotationAction.cs, Assets/Scripts/StageObjectScript/RotObjectRotate.cs, Assets/Scripts/StageObjectScript/RotObjectStick.cs
=> [Update]回転時にプレイヤー座標に補正をかけるように変更しました

Assets/Prefabs/Stage/Pf_Observer.prefab, Assets/Scenes/NewMainStage/Stage01.unity, Assets/Scenes/NewMainStage/Stage02.unity, Assets/Scenes/NewMainStage/Stage03.unity, Assets/Scenes/NewMainStage/Stage04.unity, Assets/Scenes/NewMainStage/Stage05.unity, Assets/Scenes/NewMainStage/Stage06.unity, Assets/Scenes/NewMainStage/Stage07.unity, Assets/Scenes/NewMainStage/Stage08.unity, Assets/Scripts/StageObjectScript/RotObjUnion.cs, ProjectSettings/TagManager.asset
=> [Update]メインステージの更新

Assets/VFXdeta/TestSecene_Particle02.unity
=> [Add]RotateObjectの衝突火花

Assets/Scripts/UI/TitleMovieBehaivor.cs
context.actionでは別のアクションを参照しているらしい
=> [Fix]不具合を修正

Assets/Prefabs/Sound/Pf_GameSoundManager.prefab, Assets/Prefabs/Sound/Pf_SystemSoundManager.prefab, Assets/Scripts/PlayerScript/Player.cs, Assets/Scripts/SoundScript/GameSoundManager.cs, Assets/Scripts/SoundScript/SystemSoundManager.cs
・GameSoundManagerでもBGMの再生,ラベル追加に対応しました
・SystemSoundManager,GameSoundManagerにフェードイン,フェードアウトの関数を追加しました
=> [Update]SoundManagerにフェードの機能を追加しました

Assets/Scripts/UI/RankIcon.cs, Assets/Scripts/UI/UiSeedBehavior.cs
ビジュアルスタジオのコード整列機能で色んな行が変更されていますが本当に変更した箇所は僅かです。
=> [Update]直前にクリアした際のスコアをリザルトに反映するようにしました

Assets/Scripts/Manager/SceneManager.cs
ステージにGameSoundMana...を配置しないと機能しない模様
=> [Update]ロード時にサウンドを停止する処理を追加

Assets/Scripts/UI/ResultMenu.cs
・リザルトシーンで決定入力が入ると操作を受け付けないようにしました
=> [fix]入力バグの修正

Assets/Scenes/NewMainStage/OtherScene/Result.unity
・ゴールオブジェクトの変更
・リザルトのオブジェクトの位置調整
=> [fix]ステージ修正
